export type OtherType =
  | "drop_creatures"
  | "itens_quest"
  | "monster"
  | "book"
  | "food"
  | "recipes"
  | "npc";

export interface OtherDatabaseType {
  id: string;
  name: string;
  imageUrl?: string;
  type: OtherType;
  weight?: string;
  dropBy?: string;
  sellTo?: string;
  description?: string;
  hp?: string;
  exp?: string;
  abilities?: string;
  loot?: string;
  location?: string;
  author?: string;
  notes?: string;
  text?: string;
  satiateTime?: string;
  buffs?: string;
  requirements?: string;
}

export const OTHER_DATABASE: Omit<OtherDatabaseType, "id">[] = [
  // Drop Creatures
  {
    name: "Rat Tail",
    imageUrl: "/creature-drops/Rat_tail.webp",
    type: "drop_creatures",
    weight: "1.5 oz",
    dropBy: "Rat, Giant Rat",
    sellTo: "5 Gold",
  },
  {
    name: "Ragged Cloth",
    imageUrl: "/creature-drops/Ragged_Cloth.webp",
    type: "drop_creatures",
    weight: "1 oz",
    dropBy: "Goblin",
    sellTo: "4 Gold",
  },
  {
    name: "Boletus Piece",
    imageUrl: "/creature-drops/Boletus_Piece.webp",
    type: "drop_creatures",
    weight: "2.5 oz",
    dropBy: "?",
    sellTo: "1 Gold",
  },
  {
    name: "Colocasia Seed",
    imageUrl: "/creature-drops/Colocasia_Seed.webp",
    type: "drop_creatures",
    weight: "1 oz",
    dropBy: "?",
    sellTo: "30 Gold",
  },
  {
    name: "White Wool",
    imageUrl: "/creature-drops/White_Wool.webp",
    type: "drop_creatures",
    weight: "1.1 oz",
    dropBy: "Sheep",
    sellTo: "30 Gold?",
  },
  {
    name: "Black Wool",
    imageUrl: "/creature-drops/Black_wool.webp",
    type: "drop_creatures",
    weight: "1.4 oz",
    dropBy: "Black Sheep",
    sellTo: "?",
  },
  {
    name: "Slime Essence",
    imageUrl: "/creature-drops/Slime_Essence.webp",
    type: "drop_creatures",
    weight: "1 oz",
    dropBy: "?",
    sellTo: "5 Gold",
  },
  {
    name: "Torn Paper",
    imageUrl: "/creature-drops/Torn_paper.webp",
    type: "drop_creatures",
    weight: "0.1 oz",
    dropBy: "?",
    sellTo: "?",
  },
  {
    name: "Forsaken Cross",
    imageUrl: "/creature-drops/Forsaken_cross.webp",
    type: "drop_creatures",
    weight: "4.5 oz",
    dropBy: "Occultist Apprentice",
    sellTo: "?",
  },
  {
    name: "Small Skull",
    imageUrl: "/creature-drops/Small_Skull.webp",
    type: "drop_creatures",
    weight: "5 oz",
    dropBy: "Skeleton",
    sellTo: "1 Gold",
  },
  {
    name: "Small Bones",
    imageUrl: "/creature-drops/Small_Bones.webp",
    type: "drop_creatures",
    weight: "7 oz",
    dropBy: "Skeleton",
    sellTo: "1 Gold",
  },
  {
    name: "Bones",
    imageUrl: "/creature-drops/Bones.webp",
    type: "drop_creatures",
    weight: "?",
    dropBy: "?",
    sellTo: "?",
  },
  {
    name: "Wooden Twigs",
    imageUrl: "/creature-drops/Wooden_twigs1.webp",
    type: "drop_creatures",
    weight: "",
    dropBy: "",
    sellTo: "",
  },
  {
    name: "Old Ring",
    imageUrl: "/creature-drops/Broken_ring.webp",
    type: "drop_creatures",
    weight: "1 oz",
    dropBy: "Goblin",
    sellTo: "15 Gold",
  },
  {
    name: "Bug Wings",
    imageUrl: "/creature-drops/Bug_wings.webp",
    type: "drop_creatures",
    weight: "0.1 oz",
    dropBy: "?",
    sellTo: "3 Gold",
  },

  // Items Quest
  {
    name: "Blue Ink",
    imageUrl: "/quest-items/Blue_Ink.webp",
    type: "itens_quest",
    weight: "100 oz",
    description: "A tail from a rat.",
  },
  {
    name: "Herb Bag",
    imageUrl: "/quest-items/Herb_bag.webp",
    type: "itens_quest",
    weight: "100 oz",
    description: "A cloth from a ragged.",
  },
  {
    name: "Potion Aqua Base",
    imageUrl: "/quest-items/Aqua_vial_jebidiah.webp",
    type: "itens_quest",
    weight: "100 oz",
    description: "A piece from a boletus.",
  },
  {
    name: "Jebidiah vials",
    imageUrl: "/quest-items/Jebidiah_vials.webp",
    type: "itens_quest",
    weight: "100 oz",
    description: "A seed from a colocasia.",
  },
  {
    name: "Almanac",
    imageUrl: "/quest-items/Almanac.webp",
    type: "itens_quest",
    weight: "100 oz",
    description: "A wool from a white.",
  },

  // Monster
  {
    name: "Viscid Goblin",
    type: "monster",
    hp: "195",
    exp: "277",
    abilities: "",
    loot: "0-2 Gold, Bug Wings",
  },
  {
    name: "Young Ampitere",
    type: "monster",
    hp: "1284",
    exp: "3184",
    abilities: "",
    loot: "0-25 Gold, Bluegill, Plated Legs, Hook Claw, Dragonfruit, Leather Coif",
  },
  {
    name: "Cave Troll",
    type: "monster",
    hp: "685",
    exp: "1208.48",
    abilities: "Melee (0-?), Leap (0-?), Ground Slam (0-?)",
    loot: "0-15 Gold, 0-2 Lamb Meat, Brass Legs, Ragged Cloth, Broadsword, Small Skull, Leather Boots, Gambeson",
  },
  {
    name: "Cube of Doom",
    type: "monster",
    hp: "352",
    exp: "574.58",
    abilities: "",
    loot: "0-10 Gold, 0-2 Arrows, 0-2 Slime Essence, Ironsword",
  },
  {
    name: "Pestilence Stinger",
    type: "monster",
    hp: "222",
    exp: "430.51",
    abilities: "",
    loot: "0-12 Gold, 0-3 Small Bones, 0-1 Plagued Scale, Small Skull, Spicy Stew, Spellbook: FierceThrust",
  },
  {
    name: "Giant Rat",
    type: "monster",
    hp: "170",
    exp: "213",
    abilities: "Melee (0-?), Leap (0-?)",
    loot: "0-7 Gold, 0-2 Cheese Slice, 0-2 Small Bones, Rat Tail, Cloth Vest, Yellow Beauty",
  },
  {
    name: "Goblin",
    type: "monster",
    hp: "93",
    exp: "114.29",
    abilities: "Melee (0-13)",
    loot: "0-5 Gold, Ragged Cloth",
  },
  {
    name: "Bandit",
    type: "monster",
    hp: "91",
    exp: "94.96",
    abilities: "Melee (0-5), Runs on red",
    loot: "0-5 Gold, 0-2 Bread Piece, Simple Bag, Knife, Cloth Vest, Leather Boots",
  },
  {
    name: "Skeleton",
    type: "monster",
    hp: "46",
    exp: "40.68",
    abilities: "Melee (0-9)",
    loot: "0-2 Gold, 0-2 Small Bones, Small Skull, Torch, Pumpkin, Buckler, Ironsword",
  },
  {
    name: "Black Sheep",
    type: "monster",
    hp: "39",
    exp: "",
    abilities: "Runs away",
    loot: "Lamb Meat",
  },
  {
    name: "Rat",
    type: "monster",
    hp: "35",
    exp: "41",
    abilities: "",
    loot: "0-3 Gold, 0-1 Cheese Slice",
  },
  {
    name: "Sheep",
    type: "monster",
    hp: "31",
    exp: "8.47",
    abilities: "Runs away",
    loot: "Lamb Meat, Wool",
  },
  {
    name: "Lamb",
    type: "monster",
    hp: "27",
    exp: "",
    abilities: "Runs away",
    loot: "Lamb Meat",
  },
  {
    name: "Black Lamb",
    type: "monster",
    hp: "23",
    exp: "8.47",
    abilities: "Runs away",
    loot: "",
  },
  {
    name: "Amphitere",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "",
  },
  {
    name: "Rat Shipper",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "",
  },
  {
    name: "Rubellus",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "Blue Gill",
  },
  {
    name: "Plea",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "0-7 Gold, Plea Toe, Spellbook: ShieldBlock, Broadsword, Old Gloves",
  },
  {
    name: "Tundra Rat",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "0-7 Gold, Leather Gloves, Leather Boots, Spangenhelm",
  },
  {
    name: "Pestilence Spawn",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "0-2 Bug Wings, Green Orb",
  },
  {
    name: "Digger",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "0-9 Gold, Ruby Necklace, Crystal Ring, Diamond Ring, Steel Ingot, Iron Ingot",
  },
  {
    name: "Pestilence Knight",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "0-308 Gold, 0-5 Plagued Scale, Pestilence Sword, Onyx Dagger",
  },
  {
    name: "Profaner",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "",
  },
  {
    name: "The BroodMother",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "",
  },
  {
    name: "The BlackHat",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "",
  },
  {
    name: "Tomb Diviner",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "",
  },
  {
    name: "Deadly Webcap",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "",
  },
  {
    name: "Capozzi The Bandit",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "",
  },
  {
    name: "Cave Spider",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "",
  },
  {
    name: "Terror Spider",
    type: "monster",
    hp: "",
    exp: "",
    abilities: "",
    loot: "",
  },
  {
    name: "Monk",
    type: "monster",
    hp: "",
    exp: "300",
    abilities: "Melee (0-?)",
    loot: "0-5 Gold, 0-2 Bread Piece, Old Gloves, Apple, Wooden Staff, Spellbook: Heal",
  },
  {
    name: "Orc Infantry",
    type: "monster",
    hp: "",
    exp: "854",
    abilities: "Melee (0-?), AOE (0-?)",
    loot: "0-5 Gold, 0-2 Bread Piece, Cloth Pants, Spangenhelm",
  },
  {
    name: "Minotaur",
    type: "monster",
    hp: "",
    exp: "2180",
    abilities: "Melee (0-?), Leap (0-?)",
    loot: "0-14 Gold, Chain Mail, Spangenhelm",
  },
  {
    name: "Walking Boletus",
    type: "monster",
    hp: "",
    exp: "165.83",
    abilities: "Melee (0-?), Leap AOE (10-55)",
    loot: "White Mushroom, Boletus Piece",
  },
  {
    name: "Occultist Apprentice",
    type: "monster",
    hp: "",
    exp: "116.10",
    abilities: "Melee (0-6), ConjureFire (0-18)",
    loot: "0-4 Gold, 0-2 Blueberries, Forsaken Cross, Worn Paper, Silver Dagger, Spellbook: ConjureFire",
  },
  {
    name: "Occultist Acolyte",
    type: "monster",
    hp: "",
    exp: "199.16",
    abilities: "Melee (0-6), Fireball (0-40)",
    loot: "0-4 Gold, Worn Paper, Small Mana Potion, Silver Ring, Gambeson, Dark Robe, Spellbook: Energybolt",
  },
  {
    name: "Orc General",
    type: "monster",
    hp: "",
    exp: "2494",
    abilities: "Melee (0-61), Explosive Dash 3x3 (0-?)",
    loot: "0-24 Gold, 0-2 Oranges, Brown Backpack, Meaty Stew, Longsword",
  },
  {
    name: "Orc Shaman",
    type: "monster",
    hp: "",
    exp: "1822",
    abilities:
      "Ranged 3x3 Explosion (0-?), Ranged ConjureFire (0-?), Summons up to 2 Ancient Snakes",
    loot: "",
  },

  // Book
  {
    name: "Cookbook - Spicy Stew",
    type: "book",
    location: "Caravan",
    author: "Obtained",
    notes: "Licenced Chef Quest",
    text: "To get water for your stew, you must first use a cauldron (or any other water source) with the bowl on your hand! Once you've got your water bowl, simply combine it with your cooked fish steak! And Voila! You've got your spicy stew!",
  },
  {
    name: "Cookbook - Fish Steak",
    type: "book",
    location: "Caravan",
    author: "Obtained",
    notes: "Licenced Chef Quest",
    text: "Make sure you got a knife to cut your fish! Make sure you grip it in your hands safely, and cut your fish by right - clicking on it! Once you've got your fish steaks, place them in your hands and use the stove to cook them!",
  },

  // Food
  {
    name: "Empty Bowl",
    imageUrl: "/food/Wooden_bowl_empty.webp",
    type: "food",
    satiateTime: "-",
    buffs: "",
    weight: "? oz",
    requirements: "",
    dropBy: "",
  },
  {
    name: "Cheese Wheel",
    imageUrl: "/food/Cheese_wheel.webp",
    type: "food",
    satiateTime: "-",
    buffs: "",
    weight: "",
    requirements: "",
    dropBy: "Cheese Wheel Quest",
  },
  {
    name: "Pumpkin",
    imageUrl: "/food/Pumpkin.webp",
    type: "food",
    satiateTime: "-",
    buffs: "",
    weight: "",
    requirements: "",
    dropBy: "Skeleton",
  },
  {
    name: "Potato",
    imageUrl: "/food/Raw_potato.webp",
    type: "food",
    satiateTime: "-",
    buffs: "",
    weight: "5 oz",
    requirements: "",
    dropBy: "",
  },
  {
    name: "Wheat",
    imageUrl: "/food/Wheat.webp",
    type: "food",
    satiateTime: "-",
    buffs: "",
    weight: "1 oz",
    requirements: "",
    dropBy: "What in the Barrel Quest",
  },
  {
    name: "Lamb Meat",
    imageUrl: "/food/Raw_lamb.webp",
    type: "food",
    satiateTime: "-",
    buffs: "",
    weight: "11 oz",
    requirements: "",
    dropBy: "Lamb, Sheep, Black Sheep, Cave Troll, Lamb Meat Quest",
  },
  {
    name: "White Mushroom",
    imageUrl: "/food/White_mushroom.webp",
    type: "food",
    satiateTime: "?",
    buffs: "",
    weight: "",
    requirements: "",
    dropBy: "Walking Boletus",
  },
  {
    name: "Apple",
    imageUrl: "/food/Apple.webp",
    type: "food",
    satiateTime: "?",
    buffs: "",
    weight: "",
    requirements: "",
    dropBy: "Monk",
  },
  {
    name: "Orange",
    imageUrl: "/food/Orange.webp",
    type: "food",
    satiateTime: "85",
    buffs: "",
    weight: "2.5 oz",
    requirements: "",
    dropBy: "Orc General",
  },
  {
    name: "Tofu Cube",
    imageUrl: "/food/Tofu_cube.webp",
    type: "food",
    satiateTime: "",
    buffs: "",
    weight: "",
    requirements: "",
    dropBy: "Buy from Bessie",
  },
  {
    name: "Blue Gill",
    imageUrl: "/food/Blue_Gill.webp",
    type: "food",
    satiateTime: "-",
    buffs: "",
    weight: "5 oz",
    requirements: "",
    dropBy: "Rubellus, Young Ampitere, Blue Gill Quest",
  },
  {
    name: "Red Breast",
    imageUrl: "/food/Red_Breast.webp",
    type: "food",
    satiateTime: "-",
    buffs: "",
    weight: "6 oz",
    requirements: "",
    dropBy: "",
  },
  {
    name: "Swamp Cod",
    imageUrl: "/food/Swamp_Cod.webp",
    type: "food",
    satiateTime: "-",
    buffs: "",
    weight: "4.8 oz",
    requirements: "",
    dropBy: "",
  },
  {
    name: "Grilled Fish",
    imageUrl: "/food/Grilled_fish.webp",
    type: "food",
    satiateTime: "",
    buffs: "",
    weight: "",
    requirements: "",
    dropBy: "",
  },
  {
    name: "Bread Loaf",
    imageUrl: "/food/Bread_loaf.webp",
    type: "food",
    satiateTime: "-",
    buffs: "",
    weight: "9 oz",
    requirements: "Dough + Pan",
    dropBy: "",
  },
  {
    name: "Dragonfruit",
    imageUrl: "/food/Dragonfruit.webp",
    type: "food",
    satiateTime: "300",
    buffs: "speed +1",
    weight: "3 oz",
    requirements: "",
    dropBy: "",
  },
  {
    name: "Spring Stew",
    imageUrl: "/food/Spring_stew.webp",
    type: "food",
    satiateTime: "325",
    buffs: "magic +2, speed +2",
    weight: "5 oz",
    requirements: "",
    dropBy: "",
  },
  {
    name: "Meaty Stew",
    imageUrl: "/food/Meaty_stew.webp",
    type: "food",
    satiateTime: "375",
    buffs: "damage +2, skill +2",
    weight: "5 oz",
    requirements: "",
    dropBy: "Orc General",
  },
  {
    name: "Spring Dish",
    imageUrl: "/food/Spring_dish.webp",
    type: "food",
    satiateTime: "375",
    buffs: "magic +1, speed +1",
    weight: "6 oz",
    requirements: "",
    dropBy: "",
  },
  {
    name: "Spicy Rice",
    imageUrl: "/food/Spicy_Rice.webp",
    type: "food",
    satiateTime: "425",
    buffs: "damage +6",
    weight: "6 oz",
    requirements: "",
    dropBy: "",
  },
  {
    name: "Blueberries",
    imageUrl: "/food/Blueberries.webp",
    type: "food",
    satiateTime: "75",
    buffs: "",
    weight: "0.5 oz",
    requirements: "",
    dropBy: "Occultist Apprentice",
  },

  // Recipes
  {
    name: "Dough",
    imageUrl: "/recipes/Dough.webp",
    type: "recipes",
    satiateTime: "-",
    buffs: "",
    weight: "3.5 oz",
    requirements: "Wheat + Water Bowl",
    dropBy: "",
  },
  {
    name: "Water Bowl",
    imageUrl: "/recipes/Water_Bowl.webp",
    type: "recipes",
    satiateTime: "-",
    buffs: "",
    weight: "? oz",
    requirements: "Empty Bowl + Water Well or Cooking Pot",
    dropBy: "",
  },
  {
    name: "Pumpkin Pie",
    imageUrl: "/recipes/Pumpkin_pie.webp",
    type: "recipes",
    satiateTime: "350",
    buffs: "damage +2, magic +2",
    weight: "7.5 oz",
    requirements: "Dough Bowl + Pumpkin Slice",
    dropBy: "",
  },
  {
    name: "Pumpkin Slice",
    imageUrl: "/recipes/Pumpkin_slice.webp",
    type: "recipes",
    satiateTime: "90",
    buffs: "",
    weight: "",
    requirements: "Pumpkin + Knife",
    dropBy: "",
  },
  {
    name: "Bread Piece",
    imageUrl: "/recipes/Bread_Piece.webp",
    type: "recipes",
    satiateTime: "100",
    buffs: "",
    weight: "1.1 oz",
    requirements: "Bread Loaf + Knife",
    dropBy: "Bandit, Monk, Orc Infantry",
  },
  {
    name: "Fish Steak",
    imageUrl: "/recipes/Fish_Steak.webp",
    type: "recipes",
    satiateTime: "105",
    buffs: "",
    weight: "1 oz",
    requirements: "Any raw fish + Knife",
    dropBy: "Licensed Chef Quest",
  },
  {
    name: "Cheese Slice",
    imageUrl: "/recipes/Cheese_Slice.webp",
    type: "recipes",
    satiateTime: "110",
    buffs: "",
    weight: "2 oz",
    requirements: "Cheese Wheel + Knife",
    dropBy: "Rat, Giant Rat, Tundra Rat",
  },
  {
    name: "Cooked White Mushroom",
    imageUrl: "/recipes/Cooked_mushroom.webp",
    type: "recipes",
    satiateTime: "150",
    buffs: "",
    weight: "1 oz",
    requirements: "Pan + White Mushroom",
    dropBy: "",
  },
  {
    name: "Cooked Fish Steak",
    imageUrl: "/recipes/Cooked_fish_fillet.webp",
    type: "recipes",
    satiateTime: "165",
    buffs: "",
    weight: "1 oz",
    requirements: "Fish Steak + Stove or Campfire",
    dropBy: "",
  },
  {
    name: "Rice Dish",
    imageUrl: "/recipes/Rice_Dish.webp",
    type: "recipes",
    satiateTime: "165",
    buffs: "",
    weight: "5 oz",
    requirements: "Water Bowl + Rice",
    dropBy: "",
  },
  {
    name: "Baked Potato",
    imageUrl: "/recipes/Cooked_potato.webp",
    type: "recipes",
    satiateTime: "175",
    buffs: "",
    weight: "2.5 oz",
    requirements: "Potato + Pan",
    dropBy: "",
  },
  {
    name: "Onion Rings",
    imageUrl: "/recipes/Cooked_onion_rings.webp",
    type: "recipes",
    satiateTime: "185",
    buffs: "",
    weight: "1 oz",
    requirements: "Onion + Pan",
    dropBy: "",
  },
  {
    name: "Cooked Lamb",
    imageUrl: "/recipes/Cooked_lamb.webp",
    type: "recipes",
    satiateTime: "200",
    buffs: "",
    weight: "10 oz",
    requirements: "Lamb Meat",
    dropBy: "",
  },
  {
    name: "Garlic Bread",
    imageUrl: "/recipes/Garlic_Bread.webp",
    type: "recipes",
    satiateTime: "205",
    buffs: "",
    weight: "1 oz",
    requirements: "Onion + Bread Loaf",
    dropBy: "",
  },
  {
    name: "Grilled Cheese",
    imageUrl: "/recipes/Grilled_cheese.webp",
    type: "recipes",
    satiateTime: "250",
    buffs: "",
    weight: "1.2 oz",
    requirements: "Bread Piece + Cheese Slice",
    dropBy: "Licensed Chef Quest",
  },
  {
    name: "Pumpkin Puree",
    imageUrl: "/recipes/Pumpkin_Puree.webp",
    type: "recipes",
    satiateTime: "300",
    buffs: "magic +1, skill +1",
    weight: "4.5 oz",
    requirements: "Empty Bowl + Pumpkin Slice",
    dropBy: "",
  },
  {
    name: "Sandwich",
    imageUrl: "/recipes/Sandwich.webp",
    type: "recipes",
    satiateTime: "325",
    buffs: "",
    weight: "1.5 oz",
    requirements:
      "Bread Piece + Cooked Lamb or Bread Piece + Cooked Fish Steak",
    dropBy: "",
  },
  {
    name: "Apple Pie",
    imageUrl: "/recipes/Apple_Pie.webp",
    type: "recipes",
    satiateTime: "350",
    buffs: "damage +2, magic +2",
    weight: "5 oz",
    requirements: "Dough Bowl + Apple",
    dropBy: "Licensed Chef Quest",
  },
  {
    name: "Blueberry Muffin",
    imageUrl: "/recipes/Blueberry_muffin.webp",
    type: "recipes",
    satiateTime: "350",
    buffs: "damage +2, speed +2",
    weight: "3 oz",
    requirements: "Dough Bowl + Blueberries",
    dropBy: "",
  },
  {
    name: "Quiche",
    imageUrl: "/recipes/Quiche.webp",
    type: "recipes",
    satiateTime: "350",
    buffs: "speed +3",
    weight: "2.5 oz",
    requirements: "Dough Bowl + Cheese Slice",
    dropBy: "",
  },
  {
    name: "Spicy Stew",
    imageUrl: "/recipes/Spicy_stew.webp",
    type: "recipes",
    satiateTime: "350",
    buffs: "damage +3",
    weight: "5 oz",
    requirements: "Water Bowl + Cooked Fish Steak or Cheese Slice",
    dropBy: "Licensed Chef Quest",
  },
  {
    name: "Dough Bowl",
    imageUrl: "/recipes/Dough_Bowl.webp",
    type: "recipes",
    satiateTime: "-",
    buffs: "",
    weight: "? oz",
    requirements: "Empty Bowl + Dough",
    dropBy: "",
  },
  {
    name: "Water Bowl",
    imageUrl: "/recipes/Water_Bowl.webp",
    type: "recipes",
    satiateTime: "-",
    buffs: "",
    weight: "? oz",
    requirements: "Empty Bowl + Water Well or Cooking Pot",
    dropBy: "",
  },

  // NPC
  {
    name: "Otis",
    type: "npc",
    location: "Caravan",
    sellTo:
      "Fish Steak (5 gp), Blue Gill (15 gp), Swamp Cod (35 gp), Red Breast (60 gp), Cooked Whole Fish (15 gp), Bowl of Water (6 gp), Rope (30 gp), Knife (10 gp)",
  },
  {
    name: "Hester",
    type: "npc",
    location: "Caravan",
    sellTo:
      "Simple Bag (5 gp), Brown Backpack (15 gp), Torch (3 gp), Health Potion (20 gp), Bread Piece (3 gp), Lantern (10 gp), Shovel (50 gp)",
  },
  {
    name: "Opal",
    type: "npc",
    location: "Caravan",
    sellTo:
      "Ironsword (50 gp), Buckler (50 gp), Kettle Helmet (45 gp), Gambeson (150 gp), Leather Cuisse (120 gp), Cloth Vest (35 gp), Old Gloves (50 gp), Spangenhelm (100 gp)",
  },
  {
    name: "Dewey",
    type: "npc",
    location: "Caravan",
    sellTo:
      "Cooked Fish Steak (10 gp), Cooked White Mushroom (8 gp), Spring Stew (15 gp), Spicy Rice (35 gp), Spring Dish (25 gp), Blueberry Muffin (45 gp), Iron Pan (20 gp), Wooden Bowl (5 gp)",
  },
  {
    name: "Gavin",
    type: "npc",
    location: "Caravan",
    sellTo:
      "Regeneration Ring (350 gp), Big Health Potion (60 gp), Cheese Wheel (100 gp), Orb (500 gp), Broadsword (500 gp), Berserk (500 gp), Taunt (150 gp)",
  },
  {
    name: "Zebulon",
    type: "npc",
    location: "Caravan",
    sellTo:
      "Wooden Staff (200 gp), ConjureFire (100 gp), Heal (50 gp), EnergyBolt (200 gp), Mana Potion (20 gp), Big Mana Potion (60 gp), Fireball (1200 gp), Haste (300 gp)",
  },
  {
    name: "Erastus",
    type: "npc",
    location: "Caravan",
    sellTo:
      "Arrow (1 gp), Wooden Bow (65 gp), Leather Bascinet (20 gp), Spellbook: PreciseShot (150 gp), Spellbook: Dash (300 gp), Leather Cloak (100 gp), Spellbook: ConjureArrow (200 gp)",
  },
  {
    name: "Burl",
    type: "npc",
    location: "Caravan",
    sellTo:
      "Ale Mug (10 gp), Grilled Cheese (25 gp), Bowl of Water (6 gp), Simple Bag (10 gp), Garlic Bread (25 gp), Onion Rings (15 gp)",
  },
  {
    name: "El Chad",
    type: "npc",
    location: "El Chad Village",
    sellTo:
      "House Counter (40 gp), House Box (50 gp), House Seat (20 gp), House Torch (100 gp), House Barrel (45 gp), House Chest (100 gp), House Chair (20 gp), House Depot (500 gp)",
  },
  {
    name: "Wolfram",
    type: "npc",
    location: "Capital, Docks",
    sellTo:
      "Simple Bag (10 gp), Knife (10 gp), Blue Gill (10 gp), Apple (15 gp), Paper (5 gp), Quill (5 gp), Crowbar (50 gp)",
  },
  {
    name: "Lurleen",
    type: "npc",
    location: "Capital",
    sellTo:
      "Yellow Beauty (50 gp), Hero Flower (75 gp), Kings Nose (50 gp), Rose (20 gp), Apple Pie (50 gp), Apple (10 gp)",
  },
  {
    name: "Mabel",
    type: "npc",
    location: "Capital",
    sellTo:
      "Simple Bag (50 gp), Brown Backpack (15 gp), Torch (5 gp), Empty Bowl (3 gp), Bread Piece (3 gp), Pan (15 gp), Apple (8 gp), Shovel (40 gp)",
  },
  {
    name: "Maxwell",
    type: "npc",
    location: "Capital, Temple",
    sellTo:
      "Bread Piece (3 gp), Water Bowl (5 gp), Heal (50 gp), Light (35 gp)",
  },
  {
    name: "Maude",
    type: "npc",
    location: "Capital, Trading District (upstairs)",
    sellTo:
      "Cloth Pants (10 gp), Blue Book (12 gp), Green Book (20 gp), Red Notebook (15 gp), Yellow Notebook (25 gp), Light (30 gp), LightMissile (150 gp), Heal (45 gp)",
  },
  {
    name: "Benedict",
    type: "npc",
    location: "Capital Library",
    sellTo:
      "Simple Garment (10 gp), Leather Cuisse (100 gp), Pocket Watch (30 gp), Wool (50 gp), Candle (15 gp)",
  },
  {
    name: "Reginald",
    type: "npc",
    location: "Capital Housing Area",
    sellTo:
      "House Counter (40 gp), House Box (50 gp), House Seat (20 gp), House Torch (100 gp), House Barrel (45 gp), House Chest (100 gp), House Chair (20 gp), House Depot (500 gp)",
  },
  {
    name: "Edmund",
    type: "npc",
    location: "Tutorial Village",
    sellTo:
      "Simple Bag (5 gp), Bread Loaf (35 gp), Wooden Bowl (5 gp), Holy (150 gp), Light (35 gp)",
  },
  {
    name: "Bessie",
    type: "npc",
    location: "Swamp",
    sellTo:
      "Nightshade (80 gp), Rat Tail (30 gp), Rope (25 gp), Tofu Block (7 gp), Cloth Pants (5 gp)",
  },
  {
    name: "Violet",
    type: "npc",
    location: "Swamp",
    sellTo:
      "Mana Potion (15 gp), Health Potion (15 gp), Big Health Potion (35 gp), Big Mana Potion (35 gp), EnergyHull (1200 gp), Lightning (550 gp)",
  },
  {
    name: "Eofor",
    type: "npc",
    location: "East of The Caravan",
    sellTo: "Rogue",
  },
  {
    name: "Gareth",
    type: "npc",
    location: "East of Tutorial Area",
    sellTo: "Knight",
  },
];
